### ISSUE TITLE
Does not work due to unauthorized docker.io/zabbix/zabbix-db-mariadb 

### ISSUE THREAD

**Issue by tuxdna** [br-mcc/DockerZabbix#1]
Same issue as this one:

 * https://github.com/zembutsu/zabbix-docker/issues/1

```
$ docker pull zabbix/zabbix-db-mariadb:latest
Trying to pull repository docker.io/zabbix/zabbix-db-mariadb ... 
unauthorized: authentication required
```

**Comment by tuxdna** [comment]
Should this image be okay to use instead ? 

 * https://hub.docker.com/r/monitoringartist/zabbix-db-mariadb/

**Comment by tuxdna** [comment]
This works for me 

```
version: '2'
services:
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password
  zabbix-server:
    image: monitoringartist/zabbix-3.0-xxl
    depends_on:
      - zabbix-db
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
```
